version: '3.3'

services: 
  db: 
    container_name: saas-ops-mysql
    image: mysql:5.7
    expose: 
      - 3306
    volumes:
      - ./db_data_container:/docker-entrypoint-initdb.d
      - db_data_container:/data/db
    ports:
      - 3306:3306

volumes: 
  db_data_container:
  redis: